backend/go.mod, backend/go.sum, backend/internal/security/hash.go, backend/internal/utils/hash.go, backend/test/unit/hash_test.go
Added hashing and validation functionality with bcrypt
#19
=> 19-security

backend/go.mod, backend/go.sum, backend/main.go
Set up a simple cors config for router. At the moment only allows localhost origins. 
ip of deployed frontend should be added later.
#45
=> #45 setup initial cors config for backend

.github/workflows/deploy.yml, compose.yml
Deployment with Docker Hub and Github Action Workflows
#43
=> Release-candidate

.github/workflows/deploy.yml, backend/internal/api/router.go, frontend/Dockerfile
This pull request includes the following changes:
- Refactored the Dockerfile to expose the VITE_API_URL as an environment variable.
- Updated the Dockerfile to use the updated VITE_API_URL environment variable.
- Updated the router.go file to update the allowedOrigins for the production environment.
These changes are necessary to ensure proper deployment of the application.
=> Refactor Dockerfile and router.go for deployment

.github/workflows/deploy.yml, backend/internal/api/router.go
Refactor deploy.yml to update environment variable generation and refactor router.go to update allowedOrigins for the production environment.
Fixes #43
=> Refactor deploy.yml and router.go to update environment variables and allowedOrigins

frontend/package-lock.json, frontend/package.json, frontend/src/App.tsx, frontend/src/components/LoadingSpinner.tsx, frontend/src/helpers/formatHelpers.ts, frontend/src/helpers/weatherHelpers.ts, frontend/src/types/auth.types.ts, frontend/src/types/search.types.ts, frontend/src/types/types.ts, frontend/src/types/weather.types.ts, frontend/src/views/Search.tsx, frontend/src/views/Weather.tsx, frontend/tests/weather.spec.ts
Implemented weather page on frontend, and made minor improvements to overall structure of frontend. (split type file into seperate files, implemented a loading spinner)
Closes #69
Weather page
Weather loading
Search loading spinner
=> #69 weather frontend

frontend/Dockerfile
adjusted dockerfile to override default nginx config
#80
Please add screenshots that demonstrate the changes.
=> #80 adjusted dockerfile to override default nginx config

compose.yml
updated compose.yml
#80
Please add screenshots that demonstrate the changes.
=> #80 adjusted compose file

.github/workflows/deploy.yml
This pull request fixes the issue with frontend routes returning a 404 error. The nginx configuration has been updated to handle the routes correctly. Additionally, the deploy workflow has been updated to include the `API_WEATHER_API_KEY` secret in the environment variables.
=> Fix frontend routes 404

.github/workflows/CICD-pipeline.yml, backend/docs/docs.go, backend/docs/swagger.json, backend/docs/swagger.yaml, backend/internal/api/handlers/login_handler.go, backend/internal/security/jwt.go, backend/internal/services/user_service.go, backend/test/unit/jwt_test.go, backend/test/unit/user_service_test.go, frontend/.env.example, frontend/src/types/auth.types.ts, frontend/src/views/Login.tsx, frontend/tests/login.spec.ts
Updated login to match spec correctly. The spec requires the login request be with a username and password. But we were using email and password.
The api has been updated, as well as tests and documentation.
The frontend has also been updated as well as tests.
Note: the env has been updated on the frontend. Check env.example,
closes #92
#92
=> #92 login match spec

.github/workflows/deploy.yml, .github/workflows/pull_request_test.yml
This pull request updates the image tags in the deploy.yml file. Previously, the backend and frontend images were tagged as v0.1. This PR changes the tags to use the value of the IMAGE_TAG environment variable, ensuring that the correct image versions are built and pushed.
#89
=> Update image tags in deploy.yml

README.md
Simple badges to dispaly current status of our project in readme
No issue
=> Added actions and sonarcloud badges in readme

backend/docs/docs.go, backend/docs/swagger.json, backend/docs/swagger.yaml, backend/internal/api/handlers/register_handler.go, frontend/package-lock.json, frontend/package.json, frontend/src/App.tsx, frontend/src/types/auth.types.ts, frontend/src/views/Login.tsx, frontend/src/views/Register.tsx, frontend/src/views/Search.tsx
Tried to fix the simulation error referenced in issue #99
Closes #99
Also implemented toaster on frontend to show toast messages on success/error
=> # 99 register fix

frontend/src/views/Register.tsx, frontend/tests/login.spec.ts, frontend/tests/register.spec.ts
Implemented tests for the form validation on the register page.
Primarily testing if the submit button is disabled or not with correct/incorrect input values. This should be enough as the submit handler makes an early return based on the same validation function for the values.
#102
Also changed login test to use the "page.locator" instead of "page.$" as recommended by Playwright.
As well as some minor code smell fixes in register component.
=> #102 register test

Makefile
Gave our Makefile scripts a major overhaul.
The Makefile now has following targets:
- backend-dev: Runs the backend in development mode
- frontend-dev: Runs the frontend in developmend mode
- dev: Runs the backend and frontend in development mode
- compose-down: Stops the backend and frontend containers
- build-images: Runs compose-down, then makes the external volume for the sqlite data required by backend image, then builds the backend and frontend docker images
- compose: runs build-images, then runs docker compose to start the backend and frontend containers
- compose-detach: runs build-images, then runs docker compose to start the backend and frontend containers in detached mode
- backend-test: runs backend tests
- frontend-test: runs compose-detach, then runs frontend / end-2-end …
=> #104 makefile overhaul

backend/internal/api/handlers/register_handler.go, backend/test/integration/login_integration_test.go, backend/test/integration/register_integration_test.go, backend/test/integration/search_integration_test.go, backend/test/integration/setup_integration_test.go
This pull request adds endpoint tests for the login, register, and search endpoints. The tests ensure that these endpoints are functioning correctly and returning the expected responses. The tests cover various scenarios, including valid and invalid inputs, and test the behavior of the endpoints under different conditions. These tests provide increased test coverage and help to ensure the overall quality and reliability of the application.
Closes #114
=> Add endpoint tests for login, register, and search

backend/internal/api/handlers/search_handler.go
The search functionality was updated to include sorting by title in ascending order. This ensures that the search results are displayed in a more organized and user-friendly manner.
fixes #120
=> Fix sort on search

backend/internal/api/handlers/validate_login_handler.go, backend/internal/api/router.go, backend/internal/security/jwt.go
Implementation of login validation route
#109
=> #109 Validate login with jwt

backend/docs/docs.go, backend/docs/swagger.json, backend/docs/swagger.yaml, backend/internal/api/handlers/login_handler.go, backend/internal/api/handlers/logout_handler.go, backend/internal/api/handlers/register_handler.go, backend/internal/api/handlers/search_handler.go, backend/internal/api/handlers/validate_login_handler.go, backend/internal/api/handlers/weather_handler.go, backend/internal/api/router.go, backend/main.go
Made Swagger documentation up to date with current edition of our api.
Now also has documentation for
- api/logout
- api/validate-login
Also moved the general api info comment from router.go to main.go, as it apparently has to be just above main.go in order for swag to generate the documentation properly.
#136
=> #136 fixed and updated swagger documentation

.github/workflows/deploy.yml, .github/workflows/post_deploy.yml, .github/workflows/pull_request_test.yml
Refactor test jobs, add image cleanup and post-deploy smoke tests
Refactored test jobs to run in parallel, allowing for future scalability. Added a cleanup step to remove unused Docker images on the VM to free up storage space. Also added a post-deploy workflow to run smoke tests on the production environment. This ensures that all parts of the system are operational and provides a visual indicator of successful deployment on GitHub.
Fixes #167, #164, #145.
None
=> Refactor test jobs, add image cleanup and post-deploy smoke tests

.github/workflows/post_deploy.yml, .github/workflows/pull_request_test.yml
Address issues in the smoke test related to secrets management to ensure proper functionality.
#168
Please add screenshots that demonstrate the changes.
=> Fix smoke test for secrets handling

.github/workflows/post_deploy.yml
Refactor search query in post_deploy.yml smoke test
#145
=> #145 Refactor search query in post_deploy.yml smoke test

compose.prod.yml
Added nginx service to compose.prod.yml
nginx.conf has been created directly onto production vm along with certificate.
fixes #160
=> #160 Add nginx service to compose.prod.yml

compose.prod.yml, frontend/Dockerfile.prod
minor nginx and port adjustments in order to get nginx to function properly
#160
Please add screenshots that demonstrate the changes.
=> 160-setup-https

backend/internal/api/handlers/login_handler.go, backend/internal/api/middlewares/auth_middleware.go, backend/internal/models/user.go, backend/internal/services/user_service.go, backend/test/integration/login_integration_test.go, backend/test/unit/auth_middleware_test.go
Introduce a `last_login` field to the User model, along with functions to retrieve a user by ID and update the last login timestamp. Refactor the login handler to enhance readability and ensure the last login is updated upon successful login. Improve the AuthMiddleware for better token extraction and user validation, and enhance tests with a mock database setup.
Fixes #189
none
=> Add last_login field to User model and update functionality

backend/internal/api/handlers/search_handler.go, backend/internal/database/db.go, backend/internal/models/search_log.go, backend/internal/services/search_log_service.go
Implement a logging mechanism for user search queries by creating a SearchLog model and a corresponding service function. This enhancement tracks search queries in the database, improving the ability to analyze user behavior. 
Fixes #188
none
=> #188 Add logging to the search endpoint

.github/workflows/pull_request_test.yml
Removed the setup_env job due to the env where exposed via artifacts.
closes #205
=> #205 fixed exposed envs in Pull Request Test

mandatory_2.md
Added mandatory2.md file
closes #235
none
=> #235 Add mandatory2.md

nginx.conf
Define a JSON log format in the Nginx configuration to enable structured logging. Change the access log output to stdout using the new JSON format, allowing Promtail to extract meaningful fields for analysis in Loki and Grafana.
Fixes #247
none
=> Add JSON log format for structured logging in Nginx configuration
